// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_flutter/test/features/kanji/bloc/kanji_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanji_flutter/features/kanji/models/kanji.dart' as _i2;
import 'package:kanji_flutter/features/kanji/services/kanji_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKanji_0 extends _i1.SmartFake implements _i2.Kanji {
  _FakeKanji_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KanjiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanjiService extends _i1.Mock implements _i3.KanjiService {
  MockKanjiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Kanji>> getKanjiList({
    int? page = 1,
    int? limit = 50,
    String? jlptLevel,
    int? grade,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiList, [], {
              #page: page,
              #limit: limit,
              #jlptLevel: jlptLevel,
              #grade: grade,
              #search: search,
            }),
            returnValue: _i4.Future<List<_i2.Kanji>>.value(<_i2.Kanji>[]),
          )
          as _i4.Future<List<_i2.Kanji>>);

  @override
  _i4.Future<_i2.Kanji> getKanjiById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiById, [id]),
            returnValue: _i4.Future<_i2.Kanji>.value(
              _FakeKanji_0(this, Invocation.method(#getKanjiById, [id])),
            ),
          )
          as _i4.Future<_i2.Kanji>);

  @override
  _i4.Future<_i2.Kanji> getKanjiByCharacter(String? character) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiByCharacter, [character]),
            returnValue: _i4.Future<_i2.Kanji>.value(
              _FakeKanji_0(
                this,
                Invocation.method(#getKanjiByCharacter, [character]),
              ),
            ),
          )
          as _i4.Future<_i2.Kanji>);

  @override
  _i4.Future<_i2.Kanji> createKanji(Map<String, dynamic>? kanjiData) =>
      (super.noSuchMethod(
            Invocation.method(#createKanji, [kanjiData]),
            returnValue: _i4.Future<_i2.Kanji>.value(
              _FakeKanji_0(this, Invocation.method(#createKanji, [kanjiData])),
            ),
          )
          as _i4.Future<_i2.Kanji>);

  @override
  _i4.Future<_i2.Kanji> updateKanji(int? id, Map<String, dynamic>? kanjiData) =>
      (super.noSuchMethod(
            Invocation.method(#updateKanji, [id, kanjiData]),
            returnValue: _i4.Future<_i2.Kanji>.value(
              _FakeKanji_0(
                this,
                Invocation.method(#updateKanji, [id, kanjiData]),
              ),
            ),
          )
          as _i4.Future<_i2.Kanji>);

  @override
  _i4.Future<void> deleteKanji(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKanji, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
