// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_flutter/test/features/flashcard/presentation/bloc/flashcard_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:kanji_flutter/features/flashcard/domain/entities/flashcard_card_entity.dart'
    as _i4;
import 'package:kanji_flutter/features/flashcard/domain/entities/flashcard_deck_entity.dart'
    as _i3;
import 'package:kanji_flutter/features/flashcard/domain/repositories/flashcard_repository.dart'
    as _i2;
import 'package:kanji_flutter/features/flashcard/domain/usecases/add_card_usecase.dart'
    as _i11;
import 'package:kanji_flutter/features/flashcard/domain/usecases/approve_publish_request_usecase.dart'
    as _i15;
import 'package:kanji_flutter/features/flashcard/domain/usecases/create_deck_usecase.dart'
    as _i8;
import 'package:kanji_flutter/features/flashcard/domain/usecases/delete_deck_usecase.dart'
    as _i10;
import 'package:kanji_flutter/features/flashcard/domain/usecases/get_all_decks_usecase.dart'
    as _i5;
import 'package:kanji_flutter/features/flashcard/domain/usecases/get_deck_by_id_usecase.dart'
    as _i7;
import 'package:kanji_flutter/features/flashcard/domain/usecases/get_publish_requests_usecase.dart'
    as _i14;
import 'package:kanji_flutter/features/flashcard/domain/usecases/reject_publish_request_usecase.dart'
    as _i16;
import 'package:kanji_flutter/features/flashcard/domain/usecases/remove_card_usecase.dart'
    as _i12;
import 'package:kanji_flutter/features/flashcard/domain/usecases/request_publish_usecase.dart'
    as _i13;
import 'package:kanji_flutter/features/flashcard/domain/usecases/update_deck_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFlashcardRepository_0 extends _i1.SmartFake
    implements _i2.FlashcardRepository {
  _FakeFlashcardRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlashcardDeckEntity_1 extends _i1.SmartFake
    implements _i3.FlashcardDeckEntity {
  _FakeFlashcardDeckEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlashcardCardEntity_2 extends _i1.SmartFake
    implements _i4.FlashcardCardEntity {
  _FakeFlashcardCardEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllDecksUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllDecksUseCase extends _i1.Mock
    implements _i5.GetAllDecksUseCase {
  MockGetAllDecksUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<List<_i3.FlashcardDeckEntity>> call({
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i6.Future<List<_i3.FlashcardDeckEntity>>.value(
              <_i3.FlashcardDeckEntity>[],
            ),
          )
          as _i6.Future<List<_i3.FlashcardDeckEntity>>);
}

/// A class which mocks [GetDeckByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDeckByIdUseCase extends _i1.Mock
    implements _i7.GetDeckByIdUseCase {
  MockGetDeckByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<_i3.FlashcardDeckEntity> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i6.Future<_i3.FlashcardDeckEntity>.value(
              _FakeFlashcardDeckEntity_1(this, Invocation.method(#call, [id])),
            ),
          )
          as _i6.Future<_i3.FlashcardDeckEntity>);
}

/// A class which mocks [CreateDeckUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateDeckUseCase extends _i1.Mock implements _i8.CreateDeckUseCase {
  MockCreateDeckUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<_i3.FlashcardDeckEntity> call({
    required String? name,
    String? description,
    List<int>? kanjiIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #name: name,
              #description: description,
              #kanjiIds: kanjiIds,
            }),
            returnValue: _i6.Future<_i3.FlashcardDeckEntity>.value(
              _FakeFlashcardDeckEntity_1(
                this,
                Invocation.method(#call, [], {
                  #name: name,
                  #description: description,
                  #kanjiIds: kanjiIds,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.FlashcardDeckEntity>);
}

/// A class which mocks [UpdateDeckUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDeckUseCase extends _i1.Mock implements _i9.UpdateDeckUseCase {
  MockUpdateDeckUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<_i3.FlashcardDeckEntity> call({
    required int? id,
    String? name,
    String? description,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #id: id,
              #name: name,
              #description: description,
              #isPublic: isPublic,
            }),
            returnValue: _i6.Future<_i3.FlashcardDeckEntity>.value(
              _FakeFlashcardDeckEntity_1(
                this,
                Invocation.method(#call, [], {
                  #id: id,
                  #name: name,
                  #description: description,
                  #isPublic: isPublic,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.FlashcardDeckEntity>);
}

/// A class which mocks [DeleteDeckUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteDeckUseCase extends _i1.Mock implements _i10.DeleteDeckUseCase {
  MockDeleteDeckUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<void> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [AddCardUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddCardUseCase extends _i1.Mock implements _i11.AddCardUseCase {
  MockAddCardUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<_i4.FlashcardCardEntity> call({
    required int? deckId,
    required int? kanjiId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#deckId: deckId, #kanjiId: kanjiId}),
            returnValue: _i6.Future<_i4.FlashcardCardEntity>.value(
              _FakeFlashcardCardEntity_2(
                this,
                Invocation.method(#call, [], {
                  #deckId: deckId,
                  #kanjiId: kanjiId,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.FlashcardCardEntity>);
}

/// A class which mocks [RemoveCardUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveCardUseCase extends _i1.Mock implements _i12.RemoveCardUseCase {
  MockRemoveCardUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<void> call({required int? deckId, required int? kanjiId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#deckId: deckId, #kanjiId: kanjiId}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [RequestPublishUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestPublishUseCase extends _i1.Mock
    implements _i13.RequestPublishUseCase {
  MockRequestPublishUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<void> call(int? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [deckId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [GetPublishRequestsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPublishRequestsUseCase extends _i1.Mock
    implements _i14.GetPublishRequestsUseCase {
  MockGetPublishRequestsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<List<dynamic>> call({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#status: status}),
            returnValue: _i6.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i6.Future<List<dynamic>>);
}

/// A class which mocks [ApprovePublishRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovePublishRequestUseCase extends _i1.Mock
    implements _i15.ApprovePublishRequestUseCase {
  MockApprovePublishRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<void> call(int? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [RejectPublishRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRejectPublishRequestUseCase extends _i1.Mock
    implements _i16.RejectPublishRequestUseCase {
  MockRejectPublishRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlashcardRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFlashcardRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FlashcardRepository);

  @override
  _i6.Future<void> call(int? requestId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestId, reason]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
