// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_flutter/test/features/kanji/presentation/bloc/kanji_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kanji_flutter/features/kanji/domain/entities/kanji_entity.dart'
    as _i3;
import 'package:kanji_flutter/features/kanji/domain/repositories/kanji_repository.dart'
    as _i2;
import 'package:kanji_flutter/features/kanji/domain/usecases/create_kanji_usecase.dart'
    as _i8;
import 'package:kanji_flutter/features/kanji/domain/usecases/delete_kanji_usecase.dart'
    as _i10;
import 'package:kanji_flutter/features/kanji/domain/usecases/get_kanji_by_character_usecase.dart'
    as _i7;
import 'package:kanji_flutter/features/kanji/domain/usecases/get_kanji_by_id_usecase.dart'
    as _i6;
import 'package:kanji_flutter/features/kanji/domain/usecases/get_kanji_list_usecase.dart'
    as _i4;
import 'package:kanji_flutter/features/kanji/domain/usecases/update_kanji_usecase.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKanjiRepository_0 extends _i1.SmartFake
    implements _i2.KanjiRepository {
  _FakeKanjiRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKanjiEntity_1 extends _i1.SmartFake implements _i3.KanjiEntity {
  _FakeKanjiEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetKanjiListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKanjiListUseCase extends _i1.Mock
    implements _i4.GetKanjiListUseCase {
  MockGetKanjiListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiRepository);

  @override
  _i5.Future<List<_i3.KanjiEntity>> call({
    int? page = 1,
    int? limit = 50,
    String? jlptLevel,
    int? grade,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #page: page,
              #limit: limit,
              #jlptLevel: jlptLevel,
              #grade: grade,
              #search: search,
            }),
            returnValue: _i5.Future<List<_i3.KanjiEntity>>.value(
              <_i3.KanjiEntity>[],
            ),
          )
          as _i5.Future<List<_i3.KanjiEntity>>);
}

/// A class which mocks [GetKanjiByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKanjiByIdUseCase extends _i1.Mock
    implements _i6.GetKanjiByIdUseCase {
  MockGetKanjiByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiRepository);

  @override
  _i5.Future<_i3.KanjiEntity> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<_i3.KanjiEntity>.value(
              _FakeKanjiEntity_1(this, Invocation.method(#call, [id])),
            ),
          )
          as _i5.Future<_i3.KanjiEntity>);
}

/// A class which mocks [GetKanjiByCharacterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKanjiByCharacterUseCase extends _i1.Mock
    implements _i7.GetKanjiByCharacterUseCase {
  MockGetKanjiByCharacterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiRepository);

  @override
  _i5.Future<_i3.KanjiEntity> call(String? character) =>
      (super.noSuchMethod(
            Invocation.method(#call, [character]),
            returnValue: _i5.Future<_i3.KanjiEntity>.value(
              _FakeKanjiEntity_1(this, Invocation.method(#call, [character])),
            ),
          )
          as _i5.Future<_i3.KanjiEntity>);
}

/// A class which mocks [CreateKanjiUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateKanjiUseCase extends _i1.Mock
    implements _i8.CreateKanjiUseCase {
  MockCreateKanjiUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiRepository);

  @override
  _i5.Future<_i3.KanjiEntity> call(Map<String, dynamic>? kanjiData) =>
      (super.noSuchMethod(
            Invocation.method(#call, [kanjiData]),
            returnValue: _i5.Future<_i3.KanjiEntity>.value(
              _FakeKanjiEntity_1(this, Invocation.method(#call, [kanjiData])),
            ),
          )
          as _i5.Future<_i3.KanjiEntity>);
}

/// A class which mocks [UpdateKanjiUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateKanjiUseCase extends _i1.Mock
    implements _i9.UpdateKanjiUseCase {
  MockUpdateKanjiUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiRepository);

  @override
  _i5.Future<_i3.KanjiEntity> call(int? id, Map<String, dynamic>? kanjiData) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id, kanjiData]),
            returnValue: _i5.Future<_i3.KanjiEntity>.value(
              _FakeKanjiEntity_1(
                this,
                Invocation.method(#call, [id, kanjiData]),
              ),
            ),
          )
          as _i5.Future<_i3.KanjiEntity>);
}

/// A class which mocks [DeleteKanjiUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteKanjiUseCase extends _i1.Mock
    implements _i10.DeleteKanjiUseCase {
  MockDeleteKanjiUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiRepository);

  @override
  _i5.Future<void> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
