// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_flutter/test/features/kanji_list/bloc/kanji_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kanji_flutter/features/kanji_list/models/kanji_list.dart'
    as _i2;
import 'package:kanji_flutter/features/kanji_list/services/kanji_list_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKanjiList_0 extends _i1.SmartFake implements _i2.KanjiList {
  _FakeKanjiList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KanjiListService].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanjiListService extends _i1.Mock implements _i3.KanjiListService {
  MockKanjiListService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.KanjiList>> getKanjiLists() =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiLists, []),
            returnValue: _i4.Future<List<_i2.KanjiList>>.value(
              <_i2.KanjiList>[],
            ),
          )
          as _i4.Future<List<_i2.KanjiList>>);

  @override
  _i4.Future<Map<String, dynamic>> getKanjiListById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiListById, [id]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.KanjiList> createKanjiList({
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createKanjiList, [], {
              #name: name,
              #description: description,
            }),
            returnValue: _i4.Future<_i2.KanjiList>.value(
              _FakeKanjiList_0(
                this,
                Invocation.method(#createKanjiList, [], {
                  #name: name,
                  #description: description,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.KanjiList>);

  @override
  _i4.Future<_i2.KanjiList> updateKanjiList({
    required int? id,
    String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateKanjiList, [], {
              #id: id,
              #name: name,
              #description: description,
            }),
            returnValue: _i4.Future<_i2.KanjiList>.value(
              _FakeKanjiList_0(
                this,
                Invocation.method(#updateKanjiList, [], {
                  #id: id,
                  #name: name,
                  #description: description,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.KanjiList>);

  @override
  _i4.Future<void> deleteKanjiList(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKanjiList, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addKanjiToList({
    required int? listId,
    required int? kanjiId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addKanjiToList, [], {
              #listId: listId,
              #kanjiId: kanjiId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeKanjiFromList({
    required int? listId,
    required int? kanjiId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeKanjiFromList, [], {
              #listId: listId,
              #kanjiId: kanjiId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
