// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_mobile_v1/test/features/auth/presentation/pages/login_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:kanji_mobile_v1/features/auth/domain/repositories/auth_repository.dart'
    as _i6;
import 'package:kanji_mobile_v1/features/auth/domain/usecases/get_profile_usecase.dart'
    as _i5;
import 'package:kanji_mobile_v1/features/auth/domain/usecases/login_usecase.dart'
    as _i2;
import 'package:kanji_mobile_v1/features/auth/domain/usecases/logout_usecase.dart'
    as _i4;
import 'package:kanji_mobile_v1/features/auth/domain/usecases/register_usecase.dart'
    as _i3;
import 'package:kanji_mobile_v1/features/auth/presentation/bloc/auth_bloc.dart'
    as _i8;
import 'package:kanji_mobile_v1/features/auth/presentation/bloc/auth_event.dart'
    as _i11;
import 'package:kanji_mobile_v1/features/auth/presentation/bloc/auth_state.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginUseCase_0 extends _i1.SmartFake implements _i2.LoginUseCase {
  _FakeLoginUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterUseCase_1 extends _i1.SmartFake
    implements _i3.RegisterUseCase {
  _FakeRegisterUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutUseCase_2 extends _i1.SmartFake implements _i4.LogoutUseCase {
  _FakeLogoutUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetProfileUseCase_3 extends _i1.SmartFake
    implements _i5.GetProfileUseCase {
  _FakeGetProfileUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_4 extends _i1.SmartFake
    implements _i6.AuthRepository {
  _FakeAuthRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthState_5 extends _i1.SmartFake implements _i7.AuthState {
  _FakeAuthState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i8.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginUseCase get loginUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#loginUseCase),
            returnValue: _FakeLoginUseCase_0(
              this,
              Invocation.getter(#loginUseCase),
            ),
          )
          as _i2.LoginUseCase);

  @override
  _i3.RegisterUseCase get registerUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#registerUseCase),
            returnValue: _FakeRegisterUseCase_1(
              this,
              Invocation.getter(#registerUseCase),
            ),
          )
          as _i3.RegisterUseCase);

  @override
  _i4.LogoutUseCase get logoutUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#logoutUseCase),
            returnValue: _FakeLogoutUseCase_2(
              this,
              Invocation.getter(#logoutUseCase),
            ),
          )
          as _i4.LogoutUseCase);

  @override
  _i5.GetProfileUseCase get getProfileUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getProfileUseCase),
            returnValue: _FakeGetProfileUseCase_3(
              this,
              Invocation.getter(#getProfileUseCase),
            ),
          )
          as _i5.GetProfileUseCase);

  @override
  _i6.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_4(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i6.AuthRepository);

  @override
  _i7.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_5(this, Invocation.getter(#state)),
          )
          as _i7.AuthState);

  @override
  _i9.Stream<_i7.AuthState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i7.AuthState>.empty(),
          )
          as _i9.Stream<_i7.AuthState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onTransition(
    _i10.Transition<_i11.AuthEvent, _i7.AuthState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i11.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.AuthState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.AuthEvent>(
    _i10.EventHandler<E, _i7.AuthState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i7.AuthState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
