// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_flutter/test/features/quiz/presentation/bloc/quiz_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:kanji_flutter/features/quiz/domain/entities/quiz_attempt_entity.dart'
    as _i5;
import 'package:kanji_flutter/features/quiz/domain/entities/quiz_entity.dart'
    as _i3;
import 'package:kanji_flutter/features/quiz/domain/entities/quiz_question_entity.dart'
    as _i4;
import 'package:kanji_flutter/features/quiz/domain/repositories/quiz_repository.dart'
    as _i2;
import 'package:kanji_flutter/features/quiz/domain/usecases/add_question_usecase.dart'
    as _i12;
import 'package:kanji_flutter/features/quiz/domain/usecases/approve_publish_request_usecase.dart'
    as _i22;
import 'package:kanji_flutter/features/quiz/domain/usecases/create_quiz_usecase.dart'
    as _i9;
import 'package:kanji_flutter/features/quiz/domain/usecases/delete_question_usecase.dart'
    as _i14;
import 'package:kanji_flutter/features/quiz/domain/usecases/delete_quiz_usecase.dart'
    as _i11;
import 'package:kanji_flutter/features/quiz/domain/usecases/get_all_quizzes_usecase.dart'
    as _i6;
import 'package:kanji_flutter/features/quiz/domain/usecases/get_pending_publish_requests_usecase.dart'
    as _i21;
import 'package:kanji_flutter/features/quiz/domain/usecases/get_quiz_attempt_details_usecase.dart'
    as _i19;
import 'package:kanji_flutter/features/quiz/domain/usecases/get_quiz_attempts_usecase.dart'
    as _i18;
import 'package:kanji_flutter/features/quiz/domain/usecases/get_quiz_by_id_usecase.dart'
    as _i8;
import 'package:kanji_flutter/features/quiz/domain/usecases/reject_publish_request_usecase.dart'
    as _i23;
import 'package:kanji_flutter/features/quiz/domain/usecases/reorder_questions_usecase.dart'
    as _i15;
import 'package:kanji_flutter/features/quiz/domain/usecases/request_publish_quiz_usecase.dart'
    as _i20;
import 'package:kanji_flutter/features/quiz/domain/usecases/start_quiz_attempt_usecase.dart'
    as _i16;
import 'package:kanji_flutter/features/quiz/domain/usecases/submit_quiz_attempt_usecase.dart'
    as _i17;
import 'package:kanji_flutter/features/quiz/domain/usecases/update_question_usecase.dart'
    as _i13;
import 'package:kanji_flutter/features/quiz/domain/usecases/update_quiz_usecase.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeQuizRepository_0 extends _i1.SmartFake
    implements _i2.QuizRepository {
  _FakeQuizRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuizEntity_1 extends _i1.SmartFake implements _i3.QuizEntity {
  _FakeQuizEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuizQuestionEntity_2 extends _i1.SmartFake
    implements _i4.QuizQuestionEntity {
  _FakeQuizQuestionEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuizAttemptEntity_3 extends _i1.SmartFake
    implements _i5.QuizAttemptEntity {
  _FakeQuizAttemptEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllQuizzesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllQuizzesUseCase extends _i1.Mock
    implements _i6.GetAllQuizzesUseCase {
  MockGetAllQuizzesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<List<_i3.QuizEntity>> call({
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i7.Future<List<_i3.QuizEntity>>.value(
              <_i3.QuizEntity>[],
            ),
          )
          as _i7.Future<List<_i3.QuizEntity>>);
}

/// A class which mocks [GetQuizByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuizByIdUseCase extends _i1.Mock
    implements _i8.GetQuizByIdUseCase {
  MockGetQuizByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i3.QuizEntity> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i7.Future<_i3.QuizEntity>.value(
              _FakeQuizEntity_1(this, Invocation.method(#call, [id])),
            ),
          )
          as _i7.Future<_i3.QuizEntity>);
}

/// A class which mocks [CreateQuizUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateQuizUseCase extends _i1.Mock implements _i9.CreateQuizUseCase {
  MockCreateQuizUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i3.QuizEntity> call({
    required String? title,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #title: title,
              #description: description,
            }),
            returnValue: _i7.Future<_i3.QuizEntity>.value(
              _FakeQuizEntity_1(
                this,
                Invocation.method(#call, [], {
                  #title: title,
                  #description: description,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.QuizEntity>);
}

/// A class which mocks [UpdateQuizUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateQuizUseCase extends _i1.Mock implements _i10.UpdateQuizUseCase {
  MockUpdateQuizUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i3.QuizEntity> call({
    required int? id,
    String? title,
    String? description,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #id: id,
              #title: title,
              #description: description,
              #isPublic: isPublic,
            }),
            returnValue: _i7.Future<_i3.QuizEntity>.value(
              _FakeQuizEntity_1(
                this,
                Invocation.method(#call, [], {
                  #id: id,
                  #title: title,
                  #description: description,
                  #isPublic: isPublic,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.QuizEntity>);
}

/// A class which mocks [DeleteQuizUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteQuizUseCase extends _i1.Mock implements _i11.DeleteQuizUseCase {
  MockDeleteQuizUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<void> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [AddQuestionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddQuestionUseCase extends _i1.Mock
    implements _i12.AddQuestionUseCase {
  MockAddQuestionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i4.QuizQuestionEntity> call({
    required int? quizId,
    required int? kanjiId,
    required String? questionText,
    required String? questionType,
    required List<String>? options,
    required String? correctAnswer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #quizId: quizId,
              #kanjiId: kanjiId,
              #questionText: questionText,
              #questionType: questionType,
              #options: options,
              #correctAnswer: correctAnswer,
            }),
            returnValue: _i7.Future<_i4.QuizQuestionEntity>.value(
              _FakeQuizQuestionEntity_2(
                this,
                Invocation.method(#call, [], {
                  #quizId: quizId,
                  #kanjiId: kanjiId,
                  #questionText: questionText,
                  #questionType: questionType,
                  #options: options,
                  #correctAnswer: correctAnswer,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.QuizQuestionEntity>);
}

/// A class which mocks [UpdateQuestionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateQuestionUseCase extends _i1.Mock
    implements _i13.UpdateQuestionUseCase {
  MockUpdateQuestionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i4.QuizQuestionEntity> call({
    required int? quizId,
    required int? questionId,
    String? questionText,
    String? questionType,
    List<String>? options,
    String? correctAnswer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #quizId: quizId,
              #questionId: questionId,
              #questionText: questionText,
              #questionType: questionType,
              #options: options,
              #correctAnswer: correctAnswer,
            }),
            returnValue: _i7.Future<_i4.QuizQuestionEntity>.value(
              _FakeQuizQuestionEntity_2(
                this,
                Invocation.method(#call, [], {
                  #quizId: quizId,
                  #questionId: questionId,
                  #questionText: questionText,
                  #questionType: questionType,
                  #options: options,
                  #correctAnswer: correctAnswer,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.QuizQuestionEntity>);
}

/// A class which mocks [DeleteQuestionUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteQuestionUseCase extends _i1.Mock
    implements _i14.DeleteQuestionUseCase {
  MockDeleteQuestionUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<void> call({required int? quizId, required int? questionId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #quizId: quizId,
              #questionId: questionId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ReorderQuestionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockReorderQuestionsUseCase extends _i1.Mock
    implements _i15.ReorderQuestionsUseCase {
  MockReorderQuestionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<void> call({
    required int? quizId,
    required List<Map<String, int>>? questionOrders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #quizId: quizId,
              #questionOrders: questionOrders,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [StartQuizAttemptUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockStartQuizAttemptUseCase extends _i1.Mock
    implements _i16.StartQuizAttemptUseCase {
  MockStartQuizAttemptUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i5.QuizAttemptEntity> call(int? quizId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [quizId]),
            returnValue: _i7.Future<_i5.QuizAttemptEntity>.value(
              _FakeQuizAttemptEntity_3(
                this,
                Invocation.method(#call, [quizId]),
              ),
            ),
          )
          as _i7.Future<_i5.QuizAttemptEntity>);
}

/// A class which mocks [SubmitQuizAttemptUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitQuizAttemptUseCase extends _i1.Mock
    implements _i17.SubmitQuizAttemptUseCase {
  MockSubmitQuizAttemptUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i5.QuizAttemptEntity> call({
    required int? attemptId,
    required List<Map<String, dynamic>>? answers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #attemptId: attemptId,
              #answers: answers,
            }),
            returnValue: _i7.Future<_i5.QuizAttemptEntity>.value(
              _FakeQuizAttemptEntity_3(
                this,
                Invocation.method(#call, [], {
                  #attemptId: attemptId,
                  #answers: answers,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.QuizAttemptEntity>);
}

/// A class which mocks [GetQuizAttemptsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuizAttemptsUseCase extends _i1.Mock
    implements _i18.GetQuizAttemptsUseCase {
  MockGetQuizAttemptsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<List<_i5.QuizAttemptEntity>> call(int? quizId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [quizId]),
            returnValue: _i7.Future<List<_i5.QuizAttemptEntity>>.value(
              <_i5.QuizAttemptEntity>[],
            ),
          )
          as _i7.Future<List<_i5.QuizAttemptEntity>>);
}

/// A class which mocks [GetQuizAttemptDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetQuizAttemptDetailsUseCase extends _i1.Mock
    implements _i19.GetQuizAttemptDetailsUseCase {
  MockGetQuizAttemptDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<_i5.QuizAttemptEntity> call(int? attemptId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [attemptId]),
            returnValue: _i7.Future<_i5.QuizAttemptEntity>.value(
              _FakeQuizAttemptEntity_3(
                this,
                Invocation.method(#call, [attemptId]),
              ),
            ),
          )
          as _i7.Future<_i5.QuizAttemptEntity>);
}

/// A class which mocks [RequestPublishQuizUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestPublishQuizUseCase extends _i1.Mock
    implements _i20.RequestPublishQuizUseCase {
  MockRequestPublishQuizUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<void> call(int? quizId, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#call, [quizId, message]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [GetPendingPublishRequestsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPendingPublishRequestsUseCase extends _i1.Mock
    implements _i21.GetPendingPublishRequestsUseCase {
  MockGetPendingPublishRequestsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<List<dynamic>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i7.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i7.Future<List<dynamic>>);
}

/// A class which mocks [ApprovePublishRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovePublishRequestUseCase extends _i1.Mock
    implements _i22.ApprovePublishRequestUseCase {
  MockApprovePublishRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<void> call(int? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [RejectPublishRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRejectPublishRequestUseCase extends _i1.Mock
    implements _i23.RejectPublishRequestUseCase {
  MockRejectPublishRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.QuizRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeQuizRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.QuizRepository);

  @override
  _i7.Future<void> call(int? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
