// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_mobile_v1/test/helpers/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:dartz/dartz.dart' as _i9;
import 'package:dio/dio.dart' as _i7;
import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i14;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:flutter/foundation.dart' as _i15;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i8;
import 'package:kanji_mobile_v1/core/error/failures.dart' as _i17;
import 'package:kanji_mobile_v1/core/errors/failures.dart' as _i28;
import 'package:kanji_mobile_v1/features/auth/domain/entities/auth_result.dart'
    as _i33;
import 'package:kanji_mobile_v1/features/auth/domain/entities/user.dart'
    as _i34;
import 'package:kanji_mobile_v1/features/auth/domain/repositories/auth_repository.dart'
    as _i32;
import 'package:kanji_mobile_v1/features/flashcard/domain/entities/flashcard.dart'
    as _i37;
import 'package:kanji_mobile_v1/features/flashcard/domain/entities/flashcard_deck.dart'
    as _i36;
import 'package:kanji_mobile_v1/features/flashcard/domain/entities/study_progress.dart'
    as _i38;
import 'package:kanji_mobile_v1/features/flashcard/domain/repositories/flashcard_repository.dart'
    as _i35;
import 'package:kanji_mobile_v1/features/kanji/data/datasources/kanji_remote_datasource.dart'
    as _i20;
import 'package:kanji_mobile_v1/features/kanji/data/models/kanji_model.dart'
    as _i10;
import 'package:kanji_mobile_v1/features/kanji/data/models/kanji_recognition_request.dart'
    as _i21;
import 'package:kanji_mobile_v1/features/kanji/data/models/kanji_recognition_result.dart'
    as _i11;
import 'package:kanji_mobile_v1/features/kanji/domain/entities/kanji.dart'
    as _i18;
import 'package:kanji_mobile_v1/features/kanji/domain/entities/kanji_recognition_result.dart'
    as _i19;
import 'package:kanji_mobile_v1/features/kanji/domain/repositories/kanji_repository.dart'
    as _i12;
import 'package:kanji_mobile_v1/features/kanji/domain/usecases/get_all_kanji.dart'
    as _i22;
import 'package:kanji_mobile_v1/features/kanji/domain/usecases/get_kanji_by_id.dart'
    as _i23;
import 'package:kanji_mobile_v1/features/kanji/domain/usecases/search_kanji.dart'
    as _i24;
import 'package:kanji_mobile_v1/features/kanji_list/domain/entities/kanji_list.dart'
    as _i26;
import 'package:kanji_mobile_v1/features/kanji_list/domain/repositories/kanji_list_repository.dart'
    as _i25;
import 'package:kanji_mobile_v1/features/quiz/domain/entities/question.dart'
    as _i30;
import 'package:kanji_mobile_v1/features/quiz/domain/entities/quiz.dart'
    as _i29;
import 'package:kanji_mobile_v1/features/quiz/domain/entities/quiz_result.dart'
    as _i31;
import 'package:kanji_mobile_v1/features/quiz/domain/repositories/quiz_repository.dart'
    as _i27;
import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/src/shared_preferences_legacy.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_6 extends _i1.SmartFake implements _i8.IOSOptions {
  _FakeIOSOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_7 extends _i1.SmartFake
    implements _i8.AndroidOptions {
  _FakeAndroidOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_8 extends _i1.SmartFake implements _i8.LinuxOptions {
  _FakeLinuxOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_9 extends _i1.SmartFake
    implements _i8.WindowsOptions {
  _FakeWindowsOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_10 extends _i1.SmartFake implements _i8.WebOptions {
  _FakeWebOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_11 extends _i1.SmartFake implements _i8.MacOsOptions {
  _FakeMacOsOptions_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_12<L, R> extends _i1.SmartFake implements _i9.Either<L, R> {
  _FakeEither_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKanjiModel_13 extends _i1.SmartFake implements _i10.KanjiModel {
  _FakeKanjiModel_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKanjiRecognitionResult_14 extends _i1.SmartFake
    implements _i11.KanjiRecognitionResult {
  _FakeKanjiRecognitionResult_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKanjiRepository_15 extends _i1.SmartFake
    implements _i12.KanjiRepository {
  _FakeKanjiRepository_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_0(this, Invocation.getter(#options)),
          )
          as _i2.BaseOptions);

  @override
  _i3.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_1(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i3.HttpClientAdapter);

  @override
  _i4.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_2(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i4.Transformer);

  @override
  _i5.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_3(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i5.Interceptors);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
    Invocation.setter(#options, _options),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(#httpClientAdapter, _httpClientAdapter),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
    Invocation.setter(#transformer, _transformer),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i14.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i14.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<dynamic>>);

  @override
  _i13.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i14.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i13.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_4<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<dynamic>>);

  @override
  _i13.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i14.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i14.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i13.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i13.Future<_i6.Response<T>>.value(
              _FakeResponse_4<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i13.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i3.HttpClientAdapter? httpClientAdapter,
    _i4.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_5(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i7.Dio);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i8.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_6(this, Invocation.getter(#iOptions)),
          )
          as _i8.IOSOptions);

  @override
  _i8.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_7(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i8.AndroidOptions);

  @override
  _i8.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_8(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i8.LinuxOptions);

  @override
  _i8.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_9(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i8.WindowsOptions);

  @override
  _i8.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_10(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i8.WebOptions);

  @override
  _i8.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_11(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i8.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i15.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i15.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> write({
    required String? key,
    required String? value,
    _i8.IOSOptions? iOptions,
    _i8.AndroidOptions? aOptions,
    _i8.LinuxOptions? lOptions,
    _i8.WebOptions? webOptions,
    _i8.MacOsOptions? mOptions,
    _i8.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<String?> read({
    required String? key,
    _i8.IOSOptions? iOptions,
    _i8.AndroidOptions? aOptions,
    _i8.LinuxOptions? lOptions,
    _i8.WebOptions? webOptions,
    _i8.MacOsOptions? mOptions,
    _i8.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<bool> containsKey({
    required String? key,
    _i8.IOSOptions? iOptions,
    _i8.AndroidOptions? aOptions,
    _i8.LinuxOptions? lOptions,
    _i8.WebOptions? webOptions,
    _i8.MacOsOptions? mOptions,
    _i8.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> delete({
    required String? key,
    _i8.IOSOptions? iOptions,
    _i8.AndroidOptions? aOptions,
    _i8.LinuxOptions? lOptions,
    _i8.WebOptions? webOptions,
    _i8.MacOsOptions? mOptions,
    _i8.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<Map<String, String>> readAll({
    _i8.IOSOptions? iOptions,
    _i8.AndroidOptions? aOptions,
    _i8.LinuxOptions? lOptions,
    _i8.WebOptions? webOptions,
    _i8.MacOsOptions? mOptions,
    _i8.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i13.Future<Map<String, String>>);

  @override
  _i13.Future<void> deleteAll({
    _i8.IOSOptions? iOptions,
    _i8.AndroidOptions? aOptions,
    _i8.LinuxOptions? lOptions,
    _i8.WebOptions? webOptions,
    _i8.MacOsOptions? mOptions,
    _i8.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i13.Future<bool?>.value(),
          )
          as _i13.Future<bool?>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i16.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i13.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [KanjiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanjiRepository extends _i1.Mock implements _i12.KanjiRepository {
  MockKanjiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>> getAllKanji({
    int? jlpt,
    int? grade,
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllKanji, [], {
              #jlpt: jlpt,
              #grade: grade,
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>.value(
                  _FakeEither_12<_i17.Failure, List<_i18.Kanji>>(
                    this,
                    Invocation.method(#getAllKanji, [], {
                      #jlpt: jlpt,
                      #grade: grade,
                      #search: search,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>> getKanjiById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiById, [id]),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>>.value(
                  _FakeEither_12<_i17.Failure, _i18.Kanji>(
                    this,
                    Invocation.method(#getKanjiById, [id]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>> getKanjiByCharacter(
    String? character,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiByCharacter, [character]),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>>.value(
                  _FakeEither_12<_i17.Failure, _i18.Kanji>(
                    this,
                    Invocation.method(#getKanjiByCharacter, [character]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>> searchKanji({
    String? query,
    List<int>? jlptLevels,
    List<int>? grades,
    int? minStrokes,
    int? maxStrokes,
    int? page,
    int? limit,
    String? sortBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchKanji, [], {
              #query: query,
              #jlptLevels: jlptLevels,
              #grades: grades,
              #minStrokes: minStrokes,
              #maxStrokes: maxStrokes,
              #page: page,
              #limit: limit,
              #sortBy: sortBy,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>.value(
                  _FakeEither_12<_i17.Failure, List<_i18.Kanji>>(
                    this,
                    Invocation.method(#searchKanji, [], {
                      #query: query,
                      #jlptLevels: jlptLevels,
                      #grades: grades,
                      #minStrokes: minStrokes,
                      #maxStrokes: maxStrokes,
                      #page: page,
                      #limit: limit,
                      #sortBy: sortBy,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i19.KanjiRecognitionResultEntity>>
  recognizeKanji(String? base64Image) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeKanji, [base64Image]),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, _i19.KanjiRecognitionResultEntity>
                >.value(
                  _FakeEither_12<
                    _i17.Failure,
                    _i19.KanjiRecognitionResultEntity
                  >(this, Invocation.method(#recognizeKanji, [base64Image])),
                ),
          )
          as _i13.Future<
            _i9.Either<_i17.Failure, _i19.KanjiRecognitionResultEntity>
          >);
}

/// A class which mocks [KanjiRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanjiRemoteDataSource extends _i1.Mock
    implements _i20.KanjiRemoteDataSource {
  MockKanjiRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<List<_i10.KanjiModel>> getAllKanji({
    int? jlpt,
    int? grade,
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllKanji, [], {
              #jlpt: jlpt,
              #grade: grade,
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i13.Future<List<_i10.KanjiModel>>.value(
              <_i10.KanjiModel>[],
            ),
          )
          as _i13.Future<List<_i10.KanjiModel>>);

  @override
  _i13.Future<_i10.KanjiModel> getKanjiById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiById, [id]),
            returnValue: _i13.Future<_i10.KanjiModel>.value(
              _FakeKanjiModel_13(this, Invocation.method(#getKanjiById, [id])),
            ),
          )
          as _i13.Future<_i10.KanjiModel>);

  @override
  _i13.Future<_i10.KanjiModel> getKanjiByCharacter(String? character) =>
      (super.noSuchMethod(
            Invocation.method(#getKanjiByCharacter, [character]),
            returnValue: _i13.Future<_i10.KanjiModel>.value(
              _FakeKanjiModel_13(
                this,
                Invocation.method(#getKanjiByCharacter, [character]),
              ),
            ),
          )
          as _i13.Future<_i10.KanjiModel>);

  @override
  _i13.Future<List<_i10.KanjiModel>> searchKanji({
    String? query,
    List<int>? jlptLevels,
    List<int>? grades,
    int? minStrokes,
    int? maxStrokes,
    int? page,
    int? limit,
    String? sortBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchKanji, [], {
              #query: query,
              #jlptLevels: jlptLevels,
              #grades: grades,
              #minStrokes: minStrokes,
              #maxStrokes: maxStrokes,
              #page: page,
              #limit: limit,
              #sortBy: sortBy,
            }),
            returnValue: _i13.Future<List<_i10.KanjiModel>>.value(
              <_i10.KanjiModel>[],
            ),
          )
          as _i13.Future<List<_i10.KanjiModel>>);

  @override
  _i13.Future<_i11.KanjiRecognitionResult> recognizeKanji(
    _i21.KanjiRecognitionRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recognizeKanji, [request]),
            returnValue: _i13.Future<_i11.KanjiRecognitionResult>.value(
              _FakeKanjiRecognitionResult_14(
                this,
                Invocation.method(#recognizeKanji, [request]),
              ),
            ),
          )
          as _i13.Future<_i11.KanjiRecognitionResult>);
}

/// A class which mocks [GetAllKanji].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllKanji extends _i1.Mock implements _i22.GetAllKanji {
  MockGetAllKanji() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.KanjiRepository);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>> call({
    int? jlpt,
    int? grade,
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #jlpt: jlpt,
              #grade: grade,
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>.value(
                  _FakeEither_12<_i17.Failure, List<_i18.Kanji>>(
                    this,
                    Invocation.method(#call, [], {
                      #jlpt: jlpt,
                      #grade: grade,
                      #search: search,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>);
}

/// A class which mocks [GetKanjiById].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKanjiById extends _i1.Mock implements _i23.GetKanjiById {
  MockGetKanjiById() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.KanjiRepository);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>>.value(
                  _FakeEither_12<_i17.Failure, _i18.Kanji>(
                    this,
                    Invocation.method(#call, [id]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i18.Kanji>>);
}

/// A class which mocks [SearchKanji].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchKanji extends _i1.Mock implements _i24.SearchKanji {
  MockSearchKanji() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.KanjiRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiRepository_15(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i12.KanjiRepository);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>> call({
    String? query,
    List<int>? jlptLevels,
    List<int>? grades,
    int? minStrokes,
    int? maxStrokes,
    int? page = 1,
    int? limit = 20,
    String? sortBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #query: query,
              #jlptLevels: jlptLevels,
              #grades: grades,
              #minStrokes: minStrokes,
              #maxStrokes: maxStrokes,
              #page: page,
              #limit: limit,
              #sortBy: sortBy,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>.value(
                  _FakeEither_12<_i17.Failure, List<_i18.Kanji>>(
                    this,
                    Invocation.method(#call, [], {
                      #query: query,
                      #jlptLevels: jlptLevels,
                      #grades: grades,
                      #minStrokes: minStrokes,
                      #maxStrokes: maxStrokes,
                      #page: page,
                      #limit: limit,
                      #sortBy: sortBy,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i18.Kanji>>>);
}

/// A class which mocks [KanjiListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanjiListRepository extends _i1.Mock
    implements _i25.KanjiListRepository {
  MockKanjiListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i26.KanjiList>>> getAllLists({
    String? search,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllLists, [], {
              #search: search,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i26.KanjiList>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i26.KanjiList>>(
                    this,
                    Invocation.method(#getAllLists, [], {
                      #search: search,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i26.KanjiList>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>> getListById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getListById, [id]),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>.value(
                  _FakeEither_12<_i17.Failure, _i26.KanjiList>(
                    this,
                    Invocation.method(#getListById, [id]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>> createList({
    required String? name,
    String? description,
    List<int>? kanjiIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createList, [], {
              #name: name,
              #description: description,
              #kanjiIds: kanjiIds,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>.value(
                  _FakeEither_12<_i17.Failure, _i26.KanjiList>(
                    this,
                    Invocation.method(#createList, [], {
                      #name: name,
                      #description: description,
                      #kanjiIds: kanjiIds,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>> updateList({
    required int? id,
    String? name,
    String? description,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateList, [], {
              #id: id,
              #name: name,
              #description: description,
              #isPublic: isPublic,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>.value(
                  _FakeEither_12<_i17.Failure, _i26.KanjiList>(
                    this,
                    Invocation.method(#updateList, [], {
                      #id: id,
                      #name: name,
                      #description: description,
                      #isPublic: isPublic,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, void>> deleteList(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteList, [id]),
            returnValue: _i13.Future<_i9.Either<_i17.Failure, void>>.value(
              _FakeEither_12<_i17.Failure, void>(
                this,
                Invocation.method(#deleteList, [id]),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>> addKanjiToList({
    required int? listId,
    required int? kanjiId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addKanjiToList, [], {
              #listId: listId,
              #kanjiId: kanjiId,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>.value(
                  _FakeEither_12<_i17.Failure, _i26.KanjiList>(
                    this,
                    Invocation.method(#addKanjiToList, [], {
                      #listId: listId,
                      #kanjiId: kanjiId,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>> removeKanjiFromList({
    required int? listId,
    required int? kanjiId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeKanjiFromList, [], {
              #listId: listId,
              #kanjiId: kanjiId,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>.value(
                  _FakeEither_12<_i17.Failure, _i26.KanjiList>(
                    this,
                    Invocation.method(#removeKanjiFromList, [], {
                      #listId: listId,
                      #kanjiId: kanjiId,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i26.KanjiList>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i26.KanjiList>>> getListsByJlpt({
    required String? jlptLevel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getListsByJlpt, [], {#jlptLevel: jlptLevel}),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i26.KanjiList>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i26.KanjiList>>(
                    this,
                    Invocation.method(#getListsByJlpt, [], {
                      #jlptLevel: jlptLevel,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i26.KanjiList>>>);
}

/// A class which mocks [QuizRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizRepository extends _i1.Mock implements _i27.QuizRepository {
  MockQuizRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.Either<_i28.Failure, List<_i29.Quiz>>> getAllQuizzes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllQuizzes, []),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, List<_i29.Quiz>>>.value(
                  _FakeEither_12<_i28.Failure, List<_i29.Quiz>>(
                    this,
                    Invocation.method(#getAllQuizzes, []),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, List<_i29.Quiz>>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i29.Quiz>> getQuizById(
    String? quizId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizById, [quizId]),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, _i29.Quiz>>.value(
              _FakeEither_12<_i28.Failure, _i29.Quiz>(
                this,
                Invocation.method(#getQuizById, [quizId]),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i29.Quiz>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, List<_i30.Question>>> getQuizQuestions(
    String? quizId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizQuestions, [quizId]),
            returnValue:
                _i13.Future<
                  _i9.Either<_i28.Failure, List<_i30.Question>>
                >.value(
                  _FakeEither_12<_i28.Failure, List<_i30.Question>>(
                    this,
                    Invocation.method(#getQuizQuestions, [quizId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, List<_i30.Question>>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, bool>> submitAnswer({
    required String? quizId,
    required String? questionId,
    required String? answer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnswer, [], {
              #quizId: quizId,
              #questionId: questionId,
              #answer: answer,
            }),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, bool>>.value(
              _FakeEither_12<_i28.Failure, bool>(
                this,
                Invocation.method(#submitAnswer, [], {
                  #quizId: quizId,
                  #questionId: questionId,
                  #answer: answer,
                }),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, bool>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult>> completeQuiz({
    required String? quizId,
    required int? timeSpent,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeQuiz, [], {
              #quizId: quizId,
              #timeSpent: timeSpent,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult>>.value(
                  _FakeEither_12<_i28.Failure, _i31.QuizResult>(
                    this,
                    Invocation.method(#completeQuiz, [], {
                      #quizId: quizId,
                      #timeSpent: timeSpent,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, List<_i31.QuizResult>>>
  getQuizHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getQuizHistory, []),
            returnValue:
                _i13.Future<
                  _i9.Either<_i28.Failure, List<_i31.QuizResult>>
                >.value(
                  _FakeEither_12<_i28.Failure, List<_i31.QuizResult>>(
                    this,
                    Invocation.method(#getQuizHistory, []),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, List<_i31.QuizResult>>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult>> getQuizResultById(
    String? resultId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizResultById, [resultId]),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult>>.value(
                  _FakeEither_12<_i28.Failure, _i31.QuizResult>(
                    this,
                    Invocation.method(#getQuizResultById, [resultId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, List<_i31.QuizResult>>> getQuizAttempts(
    String? quizId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuizAttempts, [quizId]),
            returnValue:
                _i13.Future<
                  _i9.Either<_i28.Failure, List<_i31.QuizResult>>
                >.value(
                  _FakeEither_12<_i28.Failure, List<_i31.QuizResult>>(
                    this,
                    Invocation.method(#getQuizAttempts, [quizId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, List<_i31.QuizResult>>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult?>> getBestScore(
    String? quizId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBestScore, [quizId]),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult?>>.value(
                  _FakeEither_12<_i28.Failure, _i31.QuizResult?>(
                    this,
                    Invocation.method(#getBestScore, [quizId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i31.QuizResult?>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, String>> startQuiz(String? quizId) =>
      (super.noSuchMethod(
            Invocation.method(#startQuiz, [quizId]),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, String>>.value(
              _FakeEither_12<_i28.Failure, String>(
                this,
                Invocation.method(#startQuiz, [quizId]),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, String>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, void>> retryQuiz(String? quizId) =>
      (super.noSuchMethod(
            Invocation.method(#retryQuiz, [quizId]),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, void>>.value(
              _FakeEither_12<_i28.Failure, void>(
                this,
                Invocation.method(#retryQuiz, [quizId]),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i30.Question>> addQuestion({
    required String? quizId,
    required String? type,
    required String? questionText,
    required List<String>? options,
    required String? correctAnswer,
    String? explanation,
    int? points = 10,
    List<String>? meanings = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addQuestion, [], {
              #quizId: quizId,
              #type: type,
              #questionText: questionText,
              #options: options,
              #correctAnswer: correctAnswer,
              #explanation: explanation,
              #points: points,
              #meanings: meanings,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i30.Question>>.value(
                  _FakeEither_12<_i28.Failure, _i30.Question>(
                    this,
                    Invocation.method(#addQuestion, [], {
                      #quizId: quizId,
                      #type: type,
                      #questionText: questionText,
                      #options: options,
                      #correctAnswer: correctAnswer,
                      #explanation: explanation,
                      #points: points,
                      #meanings: meanings,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i30.Question>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i30.Question>> updateQuestion({
    required String? quizId,
    required String? questionId,
    String? type,
    String? questionText,
    List<String>? options,
    String? correctAnswer,
    String? explanation,
    int? points,
    List<String>? meanings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuestion, [], {
              #quizId: quizId,
              #questionId: questionId,
              #type: type,
              #questionText: questionText,
              #options: options,
              #correctAnswer: correctAnswer,
              #explanation: explanation,
              #points: points,
              #meanings: meanings,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i30.Question>>.value(
                  _FakeEither_12<_i28.Failure, _i30.Question>(
                    this,
                    Invocation.method(#updateQuestion, [], {
                      #quizId: quizId,
                      #questionId: questionId,
                      #type: type,
                      #questionText: questionText,
                      #options: options,
                      #correctAnswer: correctAnswer,
                      #explanation: explanation,
                      #points: points,
                      #meanings: meanings,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i30.Question>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, void>> deleteQuestion({
    required String? quizId,
    required String? questionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteQuestion, [], {
              #quizId: quizId,
              #questionId: questionId,
            }),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, void>>.value(
              _FakeEither_12<_i28.Failure, void>(
                this,
                Invocation.method(#deleteQuestion, [], {
                  #quizId: quizId,
                  #questionId: questionId,
                }),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, void>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i32.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>> login({
    required String? account,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #account: account,
              #password: password,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>>.value(
                  _FakeEither_12<_i28.Failure, _i33.AuthResult>(
                    this,
                    Invocation.method(#login, [], {
                      #account: account,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>> register({
    required String? account,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #account: account,
              #email: email,
              #password: password,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>>.value(
                  _FakeEither_12<_i28.Failure, _i33.AuthResult>(
                    this,
                    Invocation.method(#register, [], {
                      #account: account,
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, void>>.value(
              _FakeEither_12<_i28.Failure, void>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i34.User>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, _i34.User>>.value(
              _FakeEither_12<_i28.Failure, _i34.User>(
                this,
                Invocation.method(#getProfile, []),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i34.User>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i34.User>> updateProfile({
    String? name,
    String? profileImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #profileImage: profileImage,
            }),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, _i34.User>>.value(
              _FakeEither_12<_i28.Failure, _i34.User>(
                this,
                Invocation.method(#updateProfile, [], {
                  #name: name,
                  #profileImage: profileImage,
                }),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i34.User>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, void>> changePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, void>>.value(
              _FakeEither_12<_i28.Failure, void>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, void>> forgotPassword({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [], {#email: email}),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, void>>.value(
              _FakeEither_12<_i28.Failure, void>(
                this,
                Invocation.method(#forgotPassword, [], {#email: email}),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, void>> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i13.Future<_i9.Either<_i28.Failure, void>>.value(
              _FakeEither_12<_i28.Failure, void>(
                this,
                Invocation.method(#resetPassword, [], {
                  #token: token,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>> refreshToken({
    required String? refreshToken,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {
              #refreshToken: refreshToken,
              #sessionId: sessionId,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>>.value(
                  _FakeEither_12<_i28.Failure, _i33.AuthResult>(
                    this,
                    Invocation.method(#refreshToken, [], {
                      #refreshToken: refreshToken,
                      #sessionId: sessionId,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i28.Failure, _i33.AuthResult>>);

  @override
  _i13.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<_i34.User?> getCachedUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUser, []),
            returnValue: _i13.Future<_i34.User?>.value(),
          )
          as _i13.Future<_i34.User?>);

  @override
  _i13.Future<void> clearAuthData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthData, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);
}

/// A class which mocks [FlashcardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlashcardRepository extends _i1.Mock
    implements _i35.FlashcardRepository {
  MockFlashcardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i36.FlashcardDeck>>>
  getAllDecks() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDecks, []),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i36.FlashcardDeck>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i36.FlashcardDeck>>(
                    this,
                    Invocation.method(#getAllDecks, []),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i36.FlashcardDeck>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>> getDeckById(
    String? deckId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDeckById, [deckId]),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>>.value(
                  _FakeEither_12<_i17.Failure, _i36.FlashcardDeck>(
                    this,
                    Invocation.method(#getDeckById, [deckId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>> createDeck({
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDeck, [], {
              #name: name,
              #description: description,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>>.value(
                  _FakeEither_12<_i17.Failure, _i36.FlashcardDeck>(
                    this,
                    Invocation.method(#createDeck, [], {
                      #name: name,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>> updateDeck({
    required String? deckId,
    String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeck, [], {
              #deckId: deckId,
              #name: name,
              #description: description,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>>.value(
                  _FakeEither_12<_i17.Failure, _i36.FlashcardDeck>(
                    this,
                    Invocation.method(#updateDeck, [], {
                      #deckId: deckId,
                      #name: name,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i36.FlashcardDeck>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, void>> deleteDeck(String? deckId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDeck, [deckId]),
            returnValue: _i13.Future<_i9.Either<_i17.Failure, void>>.value(
              _FakeEither_12<_i17.Failure, void>(
                this,
                Invocation.method(#deleteDeck, [deckId]),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i37.Flashcard>>> getCardsByDeck(
    String? deckId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCardsByDeck, [deckId]),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i37.Flashcard>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i37.Flashcard>>(
                    this,
                    Invocation.method(#getCardsByDeck, [deckId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i37.Flashcard>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i37.Flashcard>>> getDueCards(
    String? deckId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDueCards, [deckId]),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i37.Flashcard>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i37.Flashcard>>(
                    this,
                    Invocation.method(#getDueCards, [deckId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i37.Flashcard>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i37.Flashcard>>> getNewCards(
    String? deckId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNewCards, [deckId], {#limit: limit}),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i37.Flashcard>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i37.Flashcard>>(
                    this,
                    Invocation.method(#getNewCards, [deckId], {#limit: limit}),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i37.Flashcard>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>> getCardById(
    String? cardId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCardById, [cardId]),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>>.value(
                  _FakeEither_12<_i17.Failure, _i37.Flashcard>(
                    this,
                    Invocation.method(#getCardById, [cardId]),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>> createCard({
    required String? deckId,
    required String? kanjiId,
    required String? front,
    required String? back,
    String? hint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCard, [], {
              #deckId: deckId,
              #kanjiId: kanjiId,
              #front: front,
              #back: back,
              #hint: hint,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>>.value(
                  _FakeEither_12<_i17.Failure, _i37.Flashcard>(
                    this,
                    Invocation.method(#createCard, [], {
                      #deckId: deckId,
                      #kanjiId: kanjiId,
                      #front: front,
                      #back: back,
                      #hint: hint,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>> updateCardReview({
    required String? cardId,
    required int? quality,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCardReview, [], {
              #cardId: cardId,
              #quality: quality,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>>.value(
                  _FakeEither_12<_i17.Failure, _i37.Flashcard>(
                    this,
                    Invocation.method(#updateCardReview, [], {
                      #cardId: cardId,
                      #quality: quality,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i37.Flashcard>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, void>> deleteCard(String? cardId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [cardId]),
            returnValue: _i13.Future<_i9.Either<_i17.Failure, void>>.value(
              _FakeEither_12<_i17.Failure, void>(
                this,
                Invocation.method(#deleteCard, [cardId]),
              ),
            ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, void>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, _i38.StudyProgress>> saveProgress({
    required String? deckId,
    required int? cardsStudied,
    required int? cardsCorrect,
    required int? cardsIncorrect,
    required int? studyDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveProgress, [], {
              #deckId: deckId,
              #cardsStudied: cardsStudied,
              #cardsCorrect: cardsCorrect,
              #cardsIncorrect: cardsIncorrect,
              #studyDuration: studyDuration,
            }),
            returnValue:
                _i13.Future<_i9.Either<_i17.Failure, _i38.StudyProgress>>.value(
                  _FakeEither_12<_i17.Failure, _i38.StudyProgress>(
                    this,
                    Invocation.method(#saveProgress, [], {
                      #deckId: deckId,
                      #cardsStudied: cardsStudied,
                      #cardsCorrect: cardsCorrect,
                      #cardsIncorrect: cardsIncorrect,
                      #studyDuration: studyDuration,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, _i38.StudyProgress>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, List<_i38.StudyProgress>>>
  getProgressHistory({
    String? deckId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProgressHistory, [], {
              #deckId: deckId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, List<_i38.StudyProgress>>
                >.value(
                  _FakeEither_12<_i17.Failure, List<_i38.StudyProgress>>(
                    this,
                    Invocation.method(#getProgressHistory, [], {
                      #deckId: deckId,
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, List<_i38.StudyProgress>>>);

  @override
  _i13.Future<_i9.Either<_i17.Failure, Map<String, dynamic>>>
  getStudyStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStudyStatistics, []),
            returnValue:
                _i13.Future<
                  _i9.Either<_i17.Failure, Map<String, dynamic>>
                >.value(
                  _FakeEither_12<_i17.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getStudyStatistics, []),
                  ),
                ),
          )
          as _i13.Future<_i9.Either<_i17.Failure, Map<String, dynamic>>>);
}
