// Mocks generated by Mockito 5.4.6 from annotations
// in kanji_flutter/test/features/kanji_list/presentation/bloc/kanji_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kanji_flutter/features/kanji_list/domain/entities/kanji_list_entity.dart'
    as _i3;
import 'package:kanji_flutter/features/kanji_list/domain/repositories/kanji_list_repository.dart'
    as _i2;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/add_kanji_to_list_usecase.dart'
    as _i10;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/approve_publish_request_usecase.dart'
    as _i14;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/create_list_usecase.dart'
    as _i7;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/delete_list_usecase.dart'
    as _i9;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/get_all_lists_usecase.dart'
    as _i4;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/get_list_by_id_usecase.dart'
    as _i6;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/get_publish_requests_usecase.dart'
    as _i13;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/reject_publish_request_usecase.dart'
    as _i15;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/remove_kanji_from_list_usecase.dart'
    as _i11;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/request_publish_list_usecase.dart'
    as _i12;
import 'package:kanji_flutter/features/kanji_list/domain/usecases/update_list_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKanjiListRepository_0 extends _i1.SmartFake
    implements _i2.KanjiListRepository {
  _FakeKanjiListRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKanjiListEntity_1 extends _i1.SmartFake
    implements _i3.KanjiListEntity {
  _FakeKanjiListEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllListsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllListsUseCase extends _i1.Mock
    implements _i4.GetAllListsUseCase {
  MockGetAllListsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<List<_i3.KanjiListEntity>> call({
    String? search,
    String? type,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #search: search,
              #type: type,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Future<List<_i3.KanjiListEntity>>.value(
              <_i3.KanjiListEntity>[],
            ),
          )
          as _i5.Future<List<_i3.KanjiListEntity>>);
}

/// A class which mocks [GetListByIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListByIdUseCase extends _i1.Mock
    implements _i6.GetListByIdUseCase {
  MockGetListByIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<_i3.KanjiListEntity> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<_i3.KanjiListEntity>.value(
              _FakeKanjiListEntity_1(this, Invocation.method(#call, [id])),
            ),
          )
          as _i5.Future<_i3.KanjiListEntity>);
}

/// A class which mocks [CreateListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateListUseCase extends _i1.Mock implements _i7.CreateListUseCase {
  MockCreateListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<_i3.KanjiListEntity> call({
    required String? name,
    String? description,
    List<int>? kanjiIds,
    int? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #name: name,
              #description: description,
              #kanjiIds: kanjiIds,
              #categoryId: categoryId,
            }),
            returnValue: _i5.Future<_i3.KanjiListEntity>.value(
              _FakeKanjiListEntity_1(
                this,
                Invocation.method(#call, [], {
                  #name: name,
                  #description: description,
                  #kanjiIds: kanjiIds,
                  #categoryId: categoryId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.KanjiListEntity>);
}

/// A class which mocks [UpdateListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateListUseCase extends _i1.Mock implements _i8.UpdateListUseCase {
  MockUpdateListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<_i3.KanjiListEntity> call({
    required int? id,
    String? name,
    String? description,
    bool? isPublic,
    int? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #id: id,
              #name: name,
              #description: description,
              #isPublic: isPublic,
              #categoryId: categoryId,
            }),
            returnValue: _i5.Future<_i3.KanjiListEntity>.value(
              _FakeKanjiListEntity_1(
                this,
                Invocation.method(#call, [], {
                  #id: id,
                  #name: name,
                  #description: description,
                  #isPublic: isPublic,
                  #categoryId: categoryId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.KanjiListEntity>);
}

/// A class which mocks [DeleteListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteListUseCase extends _i1.Mock implements _i9.DeleteListUseCase {
  MockDeleteListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<void> call(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AddKanjiToListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddKanjiToListUseCase extends _i1.Mock
    implements _i10.AddKanjiToListUseCase {
  MockAddKanjiToListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<void> call({required int? listId, required int? kanjiId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#listId: listId, #kanjiId: kanjiId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [RemoveKanjiFromListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveKanjiFromListUseCase extends _i1.Mock
    implements _i11.RemoveKanjiFromListUseCase {
  MockRemoveKanjiFromListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<void> call({required int? listId, required int? kanjiId}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#listId: listId, #kanjiId: kanjiId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [RequestPublishListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRequestPublishListUseCase extends _i1.Mock
    implements _i12.RequestPublishListUseCase {
  MockRequestPublishListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<void> call(int? listId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [listId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [GetPublishRequestsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPublishRequestsUseCase extends _i1.Mock
    implements _i13.GetPublishRequestsUseCase {
  MockGetPublishRequestsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<List<dynamic>> call({String? status}) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#status: status}),
            returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i5.Future<List<dynamic>>);
}

/// A class which mocks [ApprovePublishRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockApprovePublishRequestUseCase extends _i1.Mock
    implements _i14.ApprovePublishRequestUseCase {
  MockApprovePublishRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<void> call(int? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [RejectPublishRequestUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRejectPublishRequestUseCase extends _i1.Mock
    implements _i15.RejectPublishRequestUseCase {
  MockRejectPublishRequestUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanjiListRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKanjiListRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KanjiListRepository);

  @override
  _i5.Future<void> call(int? requestId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#call, [requestId, reason]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
